SET SCHEMA 'master';
 
/* SQLINES DEMO *** abase [MyDatabase]    Script Date: 19.10.2022 22:06:02 ******/
CREATE DATABASE [MyDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyDatabase', FILENAME = N'C:UsersyunusAppDataLocalMicrosoftMicrosoft SQL Server Local DBInstancesMSSQLLocalDBMyDatabase.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = 'MyDatabase_log', FILENAME = 'C:UsersyunusAppDataLocalMicrosoftMicrosoft SQL Server Local DBInstancesMSSQLLocalDBMyDatabase.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 -- SQLINES LICENSE FOR EVALUATION USE ONLY
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MyDatabase] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
then
EXECUTE [MyDatabase].dbo.sp_fulltext_database; @action = 'enable'
end if;
 
ALTER DATABASE [MyDatabase] /* SET ANSI_NULL_DEFAULT ON */ 
 
ALTER DATABASE [MyDatabase] /* SET ANSI_NULLS ON */ 
 
ALTER DATABASE [MyDatabase] /* SET ANSI_PADDING ON */ 
 
ALTER DATABASE [MyDatabase] /* SET ANSI_WARNINGS ON */ 
 
ALTER DATABASE [MyDatabase] /* SET ARITHABORT ON */ 
 
ALTER DATABASE [MyDatabase] /* SET AUTO_CLOSE OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET AUTO_SHRINK OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET AUTO_UPDATE_STATISTICS ON */ 
 
ALTER DATABASE [MyDatabase] /* SET CURSOR_CLOSE_ON_COMMIT OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET CURSOR_DEFAULT  LOCAL */ 
 
ALTER DATABASE [MyDatabase] /* SET CONCAT_NULL_YIELDS_NULL ON */ 
 
ALTER DATABASE [MyDatabase] /* SET NUMERIC_ROUNDABORT OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET QUOTED_IDENTIFIER ON */ 
 
ALTER DATABASE [MyDatabase] /* SET RECURSIVE_TRIGGERS OFF */ 
 
ALTER DATABASE [MyDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyDatabase] /* SET AUTO_UPDATE_STATISTICS_ASYNC OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET DATE_CORRELATION_OPTIMIZATION OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET TRUSTWORTHY OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET ALLOW_SNAPSHOT_ISOLATION OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET PARAMETERIZATION SIMPLE */ 
 
ALTER DATABASE [MyDatabase] /* SET READ_COMMITTED_SNAPSHOT OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET HONOR_BROKER_PRIORITY OFF */ 
 
ALTER DATABASE [MyDatabase] /* SET RECOVERY FULL */ 
 
ALTER DATABASE [MyDatabase] SET  MULTI_USER 
 
ALTER DATABASE [MyDatabase] /* SET PAGE_VERIFY CHECKSUM */  
 
ALTER DATABASE [MyDatabase] /* SET DB_CHAINING OFF */ 
 
ALTER DATABASE [MyDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
 
ALTER DATABASE [MyDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
 
ALTER DATABASE [MyDatabase] SET DELAYED_DURABILITY = DISABLED 
 
ALTER DATABASE [MyDatabase] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [MyDatabase] SET QUERY_STORE = OFF
 
SET SCHEMA 'MyDatabase';
 
/* SQLINES DEMO *** le [dbo].[Brands]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Brands(
	BrandId int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	BrandName varchar(255) NOT NULL
);
/* SQLINES DEMO *** le [dbo].[CarImages]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE CarImages(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	CarId int NOT NULL,
	ImageName varchar(255) NULL,
	Image Bytea NULL,
	ImagePath varchar(255) NULL,
	Date Timestamp(3) NULL
);
/* SQLINES DEMO *** le [dbo].[Cars]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Cars(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	BrandId int NOT NULL,
	ColorId int NOT NULL,
	CarName varchar(255) NOT NULL,
	ModelYear int NOT NULL,
	DailyPrice Double precision NOT NULL,
	Description varchar(255) NOT NULL
);
/* SQLINES DEMO *** le [dbo].[Colors]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Colors(
	ColorId int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	ColorName varchar(255) NOT NULL
);
/* SQLINES DEMO *** le [dbo].[Customers]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Customers(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	UserId int NOT NULL,
	CompanyName varchar(255) NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[Favorites]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Favorites(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	UserId int NOT NULL,
	CarId int NOT NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[OperationClaims]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE OperationClaims(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	Name varchar(250) NOT NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[Payment]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Payment(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	CardName varchar(500) NOT NULL,
	CardNumber varchar(500) NOT NULL,
	ExpirationDate varchar(500) NOT NULL,
	SecurityCode varchar(500) NOT NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[Rentals]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Rentals(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	CarId int NOT NULL,
	CustomerId int NULL,
	UserId int NOT NULL,
	RentDate Timestamp(6) NOT NULL,
	ReturnDate Timestamp(6) NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[UserOperationClaims]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE UserOperationClaims(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	UserId int NOT NULL,
	OperationClaimId int NOT NULL,
PRIMARY KEY 
(
	Id 
) 
);
/* SQLINES DEMO *** le [dbo].[Users]    Script Date: 19.10.2022 22:06:02 ******/
/* SET ANSI_NULLS ON */
 
/* SET QUOTED_IDENTIFIER ON */
 
-- SQLINES LICENSE FOR EVALUATION USE ONLY
CREATE TABLE Users(
	Id int GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) NOT NULL,
	FirstName varchar(50) NOT NULL,
	LastName varchar(50) NOT NULL,
	Email varchar(50) NOT NULL,
	PasswordHash Bytea NOT NULL,
	PasswordSalt Bytea NOT NULL,
	Status Boolean NOT NULL,
PRIMARY KEY 
(
	Id 
) 
);
ALTER TABLE CarImages ALTER COLUMN Date  SET DEFAULT (NULL) ;
 
ALTER TABLE Rentals ALTER COLUMN ReturnDate  SET DEFAULT (NULL) ;
 
SET SCHEMA 'master';
 
ALTER DATABASE [MyDatabase] SET  READ_WRITE 
 
